#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Authors: Felix Haller <ich@ein-freier-mensch.de>
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of either or both of the following licenses:
#
# 1) the GNU Lesser General Public License version 3, as published by the
# Free Software Foundation; and/or
# 2) the GNU Lesser General Public License version 2.1, as published by
# the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranties of
# MERCHANTABILITY, SATISFACTORY QUALITY or FITNESS FOR A PARTICULAR
# PURPOSE.  See the applicable version of the GNU Lesser General Public
# License for more details.
#
# You should have received a copy of both the GNU Lesser General Public
# License version 3 and version 2.1 along with this program.  If not, see
# <http://www.gnu.org/licenses/>
#


import sys, getopt

from hinge_modules.System import System

def main(argv):
	CLIArgs = sys.argv[1:]

	if len(CLIArgs) == 0:
		from hinge_modules.GUI import GUI
		GUI()
	else:
		s = System()
		try:
			opts, args = getopt.getopt(CLIArgs,
									   "ghO:ofT:tW:wnr:",
									   ["flip",
										"help",
										"touch=",
										"toggle-touch",
										"hover-click=",
										"toggle-hover-click",
										"writing=",
										"toggle-writing",
										"normal",
										"rotate="
									   ]
			)
		except getopt.GetoptError:
			printHelp(2)

		for opt, arg in opts:
			if opt in ("-h", "--help"):
				printHelp()
			elif opt in ("-f", "--flip"):
				s.rotateDevices()
			elif opt in ("-r", "--rotate"):
				if arg in ("normal", "left", "right", "inverted"):
					s.rotateDevices(mode={"normal": 0, "left": 1, "inverted": 2, "right": 3}[arg])
				else:
					printHelp(2)
			elif opt in ("-T", "--touch"):
				if arg in ("on", "off"):
					s.tglFingerTouch(mode={"on":1, "off":0}[arg])
				else:
					printHelp(2)
			elif opt in ("-t", "--toggle-touch"):
				s.tglFingerTouch()
			elif opt in ("-O", "--hover-click"):
				if arg in ("on", "off"):
					s.tglHoverClick(mode={"off": 0, "on": 1}[arg])
				else:
					printHelp(2)
			elif opt in ("-o", "--toggle-hover-click"):
				s.tglHoverClick()
			elif opt in ("-W", "--writing"):
				if arg in ("on", "off"):
					s.tglWritingMode(mode={"on":1, "off":0}[arg])
				else:
					printHelp(2)
			elif opt in ("-w", "--toggle-writing"):
				s.tglWritingMode()
			elif opt in ("-n", "--normal"):
				s.normalMode()




def printHelp(errCode=0):
	print(
'''
Usage: hinge [options]

If started without parameters, the interactive GUI (Indicator) mode will be started.
Otherwise the following options are available.

options:
-f, --flip                     flip the rotation (toggle normal/inverted)
-T, --touch on,off             enable/disable finger touch input
-t, --toggle-touch             toggle finger touch input
-O, --hover-click on,off       enable/disable wacom hover click
-o, --toggle-hover-click       toggle wacom hover click
-n, --normal                   reset settings to default
-r, --rotate <orientation>     set a specific orientation (absolute)
                               possible values: normal, left, right, inverted
-W, --writing on,off           enables/disables writing-mode
                               (turn to "inverted", disable touch input,
                               enable hover click)
-w, --toggle-writing           toggle writing-mode
''')
	sys.exit(errCode)

if __name__ == "__main__":
	main(sys.argv)
